# Generated by Django 5.1.2 on 2024-10-29 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='name',
        ),
    ]
